### ISSUE TITLE
关于配置文件的问题

### ISSUE THREAD

**Issue by wisdomGEsLA** [TangJiakai/RecBole-FairRec#2]
1. 当我运行时：

_(base) **:~/文档/recommender-code/RecBole-FairRec-master$ python run_recbole.py -m FOCF -config_files FOCF.yaml_ 
_command line args [-m FOCF -config_files FOCF.yaml] will not be used in RecBole_

这是否意味着我的运行方式不对？

2. 另外，当我尝试修改配置文件时，例如FOCF.yaml：

  _Data settings
  LABEL_FIELD: label
  threshold: 
    rating: 3.0
  sst_attr_list: ["gender"]
  item_sst_attr_list: ["genre"]
  load_col:
    inter: [user_id,item_id,rating]
    user: [user_id,gender]
    **item: [item_id,genre]**_

开始运行后logger打印出来的读取列好像没有变化：
_load_col = {'inter': ['user_id', 'item_id', 'rating'], 'user': ['user_id', 'gender'], **'item': ['item_id']**}_

请问正确的修改配置文件的方式应该是什么呢？

**Comment by TangJiakai** [comment]
您好，很抱歉！由于事情太多了，导致耽误这么久回复。
1. 第一个问题，应该是“--config_files”，而非“-config_files”，或者您也可以用“-c”；
2. 是否是您数据集文件有问题？我这边测试之后是正常的
![image](https://user-images.githubusercontent.com/58941474/210197691-c3ba495a-44d1-4ce7-90ca-3ebf89c5195a.png)
