### ISSUE TITLE
Calculating NDCG@K of Different Groups

### ISSUE THREAD

**Issue by bhuebner3** [TangJiakai/RecBole-FairRec#4]
Is it possible to calculate the difference of NDCG@K between different groups given in the sensitive attribute? 
IE: NDCG@K for group1(males) - NDCG@K for group2(females)

**Comment by TangJiakai** [comment]
I get you! Of couse, you just calculate specific-group metric here
https://github.com/TangJiakai/RecBole-FairRec/blob/8c4ef324abddc4e9435f9c18aab9e0ba2d36386f/recbole/evaluator/base_metric.py#L67-L82
you just need pass the sensitive attribute of users and calculate group' metrics separately, you could modify this by yourself. And In future, I will consider adding this important function! (Welcome to PR!)

**Comment by Keyvantajfar** [comment]
> Is it possible to calculate the difference of NDCG@K between different groups given in the sensitive attribute? IE: NDCG@K for group1(males) - NDCG@K for group2(females)

Bro were you finally able to get that to work? i could not. thanks.

**Comment by bhuebner3** [comment]
@Keyvantajfar 
Yeah I was in a rush and couldn't figure out how to access the sensitive attribute values vector so I imported it and split the data by this attribute, then calculated the metric on each dataset. It's not good practice but it worked.

`class NDCG_sep(TopkMetric):

    def __init__(self, config):
        super().__init__(config)
        self.sst_attr_list = config['sst_attr_list']

    def calculate_metric(self, dataobject):
        sst_value = self.sst_attr_list[0]
        #sst = dataobject.get('data.' + sst_value).numpy()
        #unique_value = np.unique(sst)
        
        test_df = pd.read_csv('./dataset/geo_data/geo_data.user', sep = '\t')
        sst_column = np.array(test_df[sst_value + ':float'])
        unique_value = np.unique(sst_column)
        
        metric_dict = {}
        for value in unique_value:
            pos_index, pos_len = self.used_info(dataobject)
            pos_index = pos_index[sst_column==value]
            pos_len = pos_len[sst_column==value]
            result = self.metric_info(pos_index, pos_len)
            metric_dict.update(self.topk_result(f'ndcg_class_{value}', result))

        return metric_dict

    def metric_info(self, pos_index, pos_len):
        len_rank = np.full_like(pos_len, pos_index.shape[1])
        idcg_len = np.where(pos_len > len_rank, len_rank, pos_len)

        iranks = np.zeros_like(pos_index, dtype=np.float)
        iranks[:, :] = np.arange(1, pos_index.shape[1] + 1)
        idcg = np.cumsum(1.0 / np.log2(iranks + 1), axis=1)
        for row, idx in enumerate(idcg_len):
            idcg[row, idx:] = idcg[row, idx - 1]

        ranks = np.zeros_like(pos_index, dtype=np.float)
        ranks[:, :] = np.arange(1, pos_index.shape[1] + 1)
        dcg = 1.0 / np.log2(ranks + 1)
        dcg = np.cumsum(np.where(pos_index, dcg, 0), axis=1)

        result = dcg / idcg
        return result`

**Comment by Keyvantajfar** [comment]
> @Keyvantajfar Yeah I was in a rush and couldn't figure out how to access the sensitive attribute values vector so I imported it and split the data by this attribute, then calculated the metric on each dataset. It's not good practice but it worked.
> 
> `class NDCG_sep(TopkMetric):
> 
> ```
> def __init__(self, config):
>     super().__init__(config)
>     self.sst_attr_list = config['sst_attr_list']
> 
> def calculate_metric(self, dataobject):
>     sst_value = self.sst_attr_list[0]
>     #sst = dataobject.get('data.' + sst_value).numpy()
>     #unique_value = np.unique(sst)
>     
>     test_df = pd.read_csv('./dataset/geo_data/geo_data.user', sep = '\t')
>     sst_column = np.array(test_df[sst_value + ':float'])
>     unique_value = np.unique(sst_column)
>     
>     metric_dict = {}
>     for value in unique_value:
>         pos_index, pos_len = self.used_info(dataobject)
>         pos_index = pos_index[sst_column==value]
>         pos_len = pos_len[sst_column==value]
>         result = self.metric_info(pos_index, pos_len)
>         metric_dict.update(self.topk_result(f'ndcg_class_{value}', result))
> 
>     return metric_dict
> 
> def metric_info(self, pos_index, pos_len):
>     len_rank = np.full_like(pos_len, pos_index.shape[1])
>     idcg_len = np.where(pos_len > len_rank, len_rank, pos_len)
> 
>     iranks = np.zeros_like(pos_index, dtype=np.float)
>     iranks[:, :] = np.arange(1, pos_index.shape[1] + 1)
>     idcg = np.cumsum(1.0 / np.log2(iranks + 1), axis=1)
>     for row, idx in enumerate(idcg_len):
>         idcg[row, idx:] = idcg[row, idx - 1]
> 
>     ranks = np.zeros_like(pos_index, dtype=np.float)
>     ranks[:, :] = np.arange(1, pos_index.shape[1] + 1)
>     dcg = 1.0 / np.log2(ranks + 1)
>     dcg = np.cumsum(np.where(pos_index, dcg, 0), axis=1)
> 
>     result = dcg / idcg
>     return result`
> ```

Thanks for your help. Appreciate it.

**Comment by Keyvantajfar** [comment]
> @bhuebner3 
> Yeah I was in a rush and couldn't figure out how to access the sensitive attribute values vector so I imported it and split the data by this attribute, then calculated the metric on each dataset. It's not good practice but it worked.
thanks again, but i have some issue with this code. how can i read sensitive attributes (or all columns) of the recommendation dataset. i mean how can i retrive the recommendation subset dataset which is the iterations users for example and then i select sensitive attributes of them with a WHERE id = id from the users info dataset. what you did here just works with recbole which i dont know why but it doesnt work with other datasets due to the issue i addressed. the len of pos_index of for example 1376 wont match the len of SST_column which is the same as all the users info i have but the model only chooses 1376 interactions for its recommendation so it wont work. thanks. if you could give me your email address i'd be much happier.

**Comment by bhuebner3** [comment]
Like I said, I imported the specific dataset I used (geo_data) to access the sensitive attributes. This code will not work unless you change it, and therefore it is not good practice. Please contact the GitHub authors if you need further help.

**Comment by Keyvantajfar** [comment]
> I get you! Of couse, you just calculate specific-group metric here
> 
> https://github.com/TangJiakai/RecBole-FairRec/blob/8c4ef324abddc4e9435f9c18aab9e0ba2d36386f/recbole/evaluator/base_metric.py#L67-L82
> 
> @TangJiakai 
> you just need pass the sensitive attribute of users and calculate group' metrics separately, you could modify this by yourself. And In future, I will consider adding this important function! (Welcome to PR!)
Hello. i have a question about this if you'd let me have your email address i'd be much happier. i have scraped all the documents on the recbole but werent successful to find how the data part i have in my mind works. thanks in advance.

**Comment by Keyvantajfar** [comment]
> @bhuebner3 
> Like I said, I imported the specific dataset I used (geo_data) to access the sensitive attributes. This code will not work unless you change it, and therefore it is not good practice. Please contact the GitHub authors if you need further help.

thanks for your reply.
