### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by yangyangwuwu** [TangJiakai/RecBole-FairRec#7]
您好，在运行run_recbole.py时，出现标题处错误，请问您知道解决的方法么，谢谢！
![Snipaste_2023-03-11_16-36-42](https://user-images.githubusercontent.com/92963445/224474275-615c6d84-df27-4048-86c9-ed38b369614f.png)
![Snipaste_2023-03-11_16-36-48](https://user-images.githubusercontent.com/92963445/224474279-e595d3d9-1e6c-4ad3-8560-719ed0fba592.png)

**Comment by TangJiakai** [comment]
您好，可以参考https://github.com/TangJiakai/RecBole-FairRec/issues/3#issue-1528858684 里面相关的回答，应该可以解答您的疑惑~

**Comment by yangyangwuwu** [comment]
谢谢您的帮助，按照#3(comment)中您最后提到的修改positive_u的类型之后又出现这个问题
![Snipaste_2023-03-12_11-01-43](https://user-images.githubusercontent.com/92963445/224521807-97800ae0-73d6-4bf2-b9de-499bac965ae5.png)

**Comment by TangJiakai** [comment]
这个的话，你看看你改的代码 啥时候把positive_u改成Tensor类型了？看这个报错 应该是需要它保持list，才能进行 +=操作

**Comment by yangyangwuwu** [comment]
#3（comment）最后说改数据类型，我改了这里，然后就出现了上面的错误，是不是我改的地方不对啊，有点不太明白了
![Snipaste_2023-03-12_15-30-36](https://user-images.githubusercontent.com/92963445/224530848-4613510e-0488-407f-bb62-c618efb69453.png)

**Comment by TangJiakai** [comment]
这样吧，根据第一次你说的bug，那就是什么时候tensor作为index的时候，你就临时转换这个tensor为对应的long类型，这样看可以吗？

**Comment by yangyangwuwu** [comment]
谢谢您，问题已经解决了
