### ISSUE TITLE
where do you make data.sst ? where does it turns into an array of 1s and 2s ??

### ISSUE THREAD

**Issue by Keyvantajfar** [TangJiakai/RecBole-FairRec#9]
# where do you make data.sst ? where does it turns into an array of 1s and 2s ?? i want to find it to know which one is male or female or other features and also turn it to 0s and 1s. thanks

**Comment by Keyvantajfar** [comment]
> # where do you make data.sst ? where does it turns into an array of 1s and 2s ?? i want to find it to know which one is male or female or other features and also turn it to 0s and 1s. thanks

@TangJiakai thanks for your attention.

**Comment by Keyvantajfar** [comment]
> @peteryang1031 
if you would help me I'd be much happy thank you.

**Comment by a951160430** [comment]
您好，请问您跑通LightGCL的代码了吗

**Comment by Keyvantajfar** [comment]
Thanks for not maintaining this repo anymore :(
